"""Postgres implementation of the db seam (contract: db/__init__.py).

The only module that imports psycopg — loaded lazily by create_database,
so sqlite deployments never pay for it.
"""

from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from typing import Any

import psycopg
from psycopg_pool import ConnectionPool

from app.services.db import UniqueViolationError

# The canonical schema strings are written in the seam's shared dialect;
# this is the one construct with no common form (spec §R2). GENERATED BY
# DEFAULT (not ALWAYS) so the PR3 import tool may insert explicit ids.
_PK_CANONICAL = "INTEGER PRIMARY KEY AUTOINCREMENT"
_PK_POSTGRES = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


class _DualRow(Sequence):
    """Mapping + positional row access (the seam's Row contract)."""

    __slots__ = ("_names", "_values")

    def __init__(self, names: tuple[str, ...], values: tuple[Any, ...]) -> None:
        self._names = names
        self._values = values

    def __getitem__(self, key):
        if isinstance(key, str):
            return self._values[self._names.index(key)]
        return self._values[key]

    def __len__(self) -> int:
        return len(self._values)


def _dual_row_factory(cursor: psycopg.Cursor) -> Any:
    names = tuple(d.name for d in cursor.description or ())

    def make(values: Sequence[Any]) -> _DualRow:
        return _DualRow(names, tuple(values))

    return make


class PostgresConnection:
    """Thin proxy over psycopg.Connection: qmark translation + the seam's
    error mapping on execute(); executescript() renders the canonical DDL
    and propagates driver errors unmapped (contract)."""

    dialect = "postgres"

    def __init__(self, raw: psycopg.Connection, pool: ConnectionPool) -> None:
        self._raw = raw
        self._pool = pool

    def execute(self, sql: str, params: object = ()):
        # The contract forbids literal '?' AND literal '%' outside
        # placeholders: '?' because of this textual translation, '%'
        # because psycopg's placeholder parser rejects any other use
        # (params=() always routes through it).
        try:
            return self._raw.execute(sql.replace("?", "%s"), params)
        except psycopg.errors.UniqueViolation as exc:
            raise UniqueViolationError(str(exc)) from exc

    def executescript(self, ddl: str) -> None:
        self._raw.execute(ddl.replace(_PK_CANONICAL, _PK_POSTGRES))

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        # raw_connect contract: "close" releases — return to the pool
        # (putconn rolls back any open transaction), never sever the socket.
        self._pool.putconn(self._raw)


class PostgresDatabase:
    """The seam's Postgres backend: one pool, fixed sizing (no knobs)."""

    dialect = "postgres"

    def __init__(self, dsn: str) -> None:
        self._pool = ConnectionPool(
            dsn,
            min_size=1,
            max_size=5,
            timeout=30,
            open=True,
            configure=lambda conn: setattr(conn, "row_factory", _dual_row_factory),
        )
        # open=True alone does NOT connect eagerly (failures would only
        # surface as a PoolTimeout on first checkout); wait() forces the
        # first connection now so a bad DSN fails loudly at boot, with the
        # pool's own diagnostics (spec §R5). psycopg-pool's failure log
        # names host/port, never the password.
        self._pool.wait(timeout=30.0)

    @contextmanager
    def connect(self) -> Iterator[PostgresConnection]:
        # pool.connection() commits on clean exit, rolls back on exception,
        # and returns the connection to the pool — the seam's connect()
        # semantics exactly.
        with self._pool.connection() as raw:
            yield PostgresConnection(raw, self._pool)

    def raw_connect(self) -> PostgresConnection:
        return PostgresConnection(self._pool.getconn(), self._pool)

    def close(self) -> None:
        self._pool.close()
