#!/usr/bin/env python3
"""Generate THIRD-PARTY-NOTICES.md (B17, #58).

Collects, with full license texts:
  1. Python packages the image ships — the ``uv export --no-dev
     --group models`` set (runtime deps + spaCy/ginza models and their
     transitives), license text read from the installed distribution's
     metadata (run via ``uv run --project backend`` so the venv is
     importable).
  2. Frontend production dependencies — ``license-checker-rseidelsohn``
     over frontend/ (the set that reaches dist/).
  3. Curated entries (scripts/curated-licenses.yaml) — the Hunspell
     dictionaries, texts from committed files fetched at a pinned
     upstream revision.

Debian base-image packages are attributed by the /usr/share/doc/*/copyright
files that remain in the image (stated in the output header).

The output describes the linux/CPython 3.13 container image: requirement
markers are evaluated against a fixed IMAGE_ENV (not the machine running
the script), so the package LIST is platform-independent — a pure
function of uv.lock, package-lock.json, and the curated data. License
TEXTS, however, are read from the distributions actually installed in
the local venv/node_modules, which are platform-specific wheels/packages
(e.g. numpy's macOS wheel ships numpy/.dylibs/*, its linux wheel ships
numpy.libs/*). So the script must be run on linux, matching the image
and CI, or the generated notices will misattribute license text and
every CI run will show drift. See the platform guard in main().

Usage (repo root, on linux):  uv run --project backend python scripts/collect-licenses.py
CI drift check:                run it, then `git diff --exit-code THIRD-PARTY-NOTICES.md`
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from importlib import metadata
from pathlib import Path

import yaml
from packaging.markers import Marker  # transitive dep of the backend venv

# The image's environment (linux/amd64, CPython 3.13). Markers are evaluated
# against THIS, never the local platform, so dev and CI agree byte-for-byte.
IMAGE_ENV = {
    "sys_platform": "linux",
    "platform_system": "Linux",
    "os_name": "posix",
    "platform_machine": "x86_64",
    "platform_python_implementation": "CPython",
    "python_version": "3.13",
    "python_full_version": "3.13.0",
    "implementation_name": "cpython",
    "extra": "",
}

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "THIRD-PARTY-NOTICES.md"
CURATED = REPO / "scripts" / "curated-licenses.yaml"

HEADER = """\
# Third-Party Notices

Fabulous Writing is MIT-licensed (see LICENSE). The distributed container
image and application bundle include the third-party components below,
reproduced with their license texts as those licenses require.

Debian packages in the base image keep their license and copyright
information in `/usr/share/doc/<package>/copyright` inside the image.

This file is generated by `scripts/collect-licenses.py`; CI fails if it
is out of date. Do not edit by hand.
"""

# Python packages whose wheels ship no license file at all (verified by
# inspecting dist.files) but that are distributed in the image — full
# texts fetched from upstream and committed, same pattern as the curated
# Hunspell dictionaries.
SUPPLEMENTAL_TEXTS = {
    "ja-ginza": "scripts/curated-license-texts/ja-ginza.txt",
    "sudachipy": "scripts/curated-license-texts/sudachipy.txt",
}


def python_requirements() -> list[tuple[str, str]]:
    """Pinned (name, version) pairs for the image — marker-filtered.

    --group models pulls in exactly what the image's
    `uv sync --locked --no-dev --group models` installs: the spaCy/ginza
    model wheels (exported as `name @ https://...` URL lines) and their
    transitives (sudachipy, sudachidict-core, plac, ...).
    """
    out = subprocess.run(
        [
            "uv", "export", "--no-dev", "--group", "models",
            "--no-hashes", "--format", "requirements-txt",
        ],
        cwd=REPO / "backend",
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    pins = []
    for line in out.splitlines():
        line = line.strip()
        match = re.match(r"^([A-Za-z0-9._-]+)==([^ ;]+)\s*(?:;\s*(.+))?$", line)
        if match:
            name, version, marker = match.group(1), match.group(2), match.group(3)
        else:
            # URL-pinned wheels from [tool.uv.sources], e.g.
            # `en-core-web-sm @ https://.../en_core_web_sm-3.8.0-py3-none-any.whl`
            url_match = re.match(r"^([A-Za-z0-9._-]+) @ \S+\s*(?:;\s*(.+))?$", line)
            if not url_match:
                continue
            name, marker = url_match.group(1), url_match.group(2)
            version = ""  # resolved from installed metadata below
        # The export is universal (all platforms). Keep only what the
        # linux/CPython image actually ships — e.g. colorama (win32-only)
        # is exported but never installed in the image.
        if marker and not Marker(marker).evaluate(IMAGE_ENV):
            continue
        if not version:
            version = metadata.version(name)
        pins.append((name, version))
    if not pins:
        raise SystemExit("uv export produced no pinned requirements")
    return sorted(pins, key=lambda p: p[0].lower())


def python_license(name: str) -> tuple[str, str]:
    try:
        dist = metadata.distribution(name)
    except metadata.PackageNotFoundError:
        raise SystemExit(
            f"'{name}' is in the uv export for the image but not installed"
            " locally — run `uv sync --locked` in backend/ first"
        ) from None
    meta = dist.metadata
    spdx = meta.get("License-Expression") or ""
    if not spdx:
        classifiers = [
            c.removeprefix("License :: OSI Approved :: ")
            for c in meta.get_all("Classifier", [])
            if c.startswith("License ::")
        ]
        spdx = "; ".join(classifiers) or (meta.get("License") or "UNKNOWN")
    texts = []
    for file in dist.files or []:
        parts = [part.lower() for part in file.parts]
        if not parts or ".dist-info" not in parts[0]:
            continue
        if not ("licenses" in parts or parts[-1].startswith(("license", "copying", "notice"))):
            continue
        # PackagePath is rooted at site-packages; locate() gives the real
        # path (dist.read_text() would resolve relative to .dist-info and
        # silently return None for every file).
        located = file.locate()
        if located.is_file():
            texts.append(located.read_text(encoding="utf-8", errors="replace"))
    if texts:
        return spdx, "\n\n".join(texts)
    normalized = name.lower().replace("_", "-")
    for key, rel_path in SUPPLEMENTAL_TEXTS.items():
        if key.lower().replace("_", "-") != normalized:
            continue
        text_path = REPO / rel_path
        if not text_path.is_file() or not text_path.read_text(encoding="utf-8").strip():
            raise SystemExit(
                f"'{name}': supplemental text_file '{rel_path}' is missing"
                " or empty — full license texts are required"
            )
        return spdx, text_path.read_text(encoding="utf-8", errors="replace")
    return spdx, "(license text not shipped in wheel; see project page)"


def npm_packages() -> dict[str, dict]:
    out = subprocess.run(
        [
            "npx", "--yes", "license-checker-rseidelsohn@4",
            "--production", "--json", "--excludePrivatePackages",
        ],
        cwd=REPO / "frontend",
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return json.loads(out)


def render(sections: list[tuple[str, list[tuple[str, str, str, str]]]]) -> str:
    lines = [HEADER]
    for title, entries in sections:
        lines.append(f"\n## {title}\n")
        for name, version, license_id, text in entries:
            lines.append(f"\n### {name} {version}\n")
            lines.append(f"License: {license_id}\n")
            # 4-backtick fence: npm licenseFile sometimes points at a README
            # whose own ``` fences would otherwise break the structure.
            lines.append("````text")
            lines.append(text.strip() or "(no text)")
            lines.append("````")
    return "\n".join(lines) + "\n"


def main() -> int:
    if sys.platform != "linux" and "--force-platform" not in sys.argv:
        raise SystemExit(
            "collect-licenses.py must be run on linux: the package LIST is "
            "platform-independent (marker-filtered against IMAGE_ENV), but "
            "license TEXTS are read from the distributions actually "
            "installed in the local venv/node_modules, which are "
            "platform-specific wheels (e.g. numpy's macOS wheel ships "
            "numpy/.dylibs/*, its linux wheel ships numpy.libs/*). Run this "
            "inside a linux container matching the image/CI. Pass "
            "--force-platform to override at your own risk."
        )

    curated_doc = yaml.safe_load(CURATED.read_text(encoding="utf-8"))
    if "<" in str(curated_doc.get("revision", "<")):
        raise SystemExit("curated-licenses.yaml: revision still unverified")
    curated = curated_doc["entries"]
    for entry in curated:
        if "<" in entry["license"]:
            raise SystemExit(f"curated entry '{entry['name']}' still unverified")
        text_path = REPO / entry["text_file"]
        if not text_path.is_file() or not text_path.read_text(encoding="utf-8").strip():
            raise SystemExit(
                f"curated entry '{entry['name']}': text_file"
                f" '{entry['text_file']}' is missing or empty — full license"
                " texts are required"
            )

    python_entries = []
    for name, version in python_requirements():
        spdx, text = python_license(name)
        python_entries.append((name, version, spdx, text))

    npm_entries = []
    for key, info in sorted(npm_packages().items()):
        name, _, version = key.rpartition("@")
        license_file = info.get("licenseFile")
        text = (
            Path(license_file).read_text(encoding="utf-8", errors="replace")
            if license_file and Path(license_file).is_file()
            else "(license text not shipped; see repository)"
        )
        licenses = info.get("licenses", "UNKNOWN")
        if isinstance(licenses, list):
            licenses = " OR ".join(licenses)
        npm_entries.append((name, version, str(licenses), text))

    curated_entries = [
        (
            entry["name"],
            str(entry["version"]),
            entry["license"],
            f"Source: {entry['source']}\n\n"
            + (REPO / entry["text_file"]).read_text(encoding="utf-8", errors="replace"),
        )
        for entry in curated
    ]

    OUTPUT.write_text(
        render(
            [
                ("Python (backend runtime + language models)", python_entries),
                ("JavaScript (bundled frontend)", npm_entries),
                ("Hunspell dictionaries", curated_entries),
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size // 1024} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
